<?xml version="1.0" ?>
<robot name="cranebot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find crane_description)/urdf/cranebot.gazebo" />

  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.4 0.0 1.0"/>
  </material>

  <xacro:property name="length" value="14"/>
  <xacro:property name="width" value="0.25"/>
  <xacro:property name="height" value="0.5"/>
  <xacro:property name="boom_mass" value="0.5"/> <!--1.0-->

  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <link name="link1">
    <!-- <collision>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <geometry>
        <box size="17 5 2"/>
      </geometry>
    </collision> -->
    <visual>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="15 3 1"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="1.0" iyy="0.0" iyz="1.0" izz="0.0"/>
    </inertial>
  </link>

  <joint name="azimuth" type="revolute"> <!--azimuth-->
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="-6 0 1" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit effort="10000" lower="-3.14" upper="3.14" velocity="0.01"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.8" length="0.2"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="elevation" type="revolute"> <!--elevation-->
    <parent link="link2"/>
    <child link="prlink1"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit effort="10000" lower="0" upper="1.5" velocity="0.1"/>
    <dynamics damping="0.0" friction="100.0"/>
  </joint>

<!-- prismatic start -->

  <link name="prlink1">
    <visual>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${boom_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="prj1" type="prismatic">
    <parent link="prlink1"/>
    <child link="prlink2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10000" lower="0" upper="14" velocity="0.05"/>
  </joint>

  <link name="prlink2">
    <visual>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${boom_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="prj2" type="prismatic">
    <parent link="prlink2"/>
    <child link="prlink3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10000" lower="0" upper="14" velocity="0.05"/>
  </joint>

  <link name="prlink3">
    <visual>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${boom_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="prj3" type="prismatic">
    <parent link="prlink3"/>
    <child link="prlink4"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10000" lower="0" upper="14" velocity="0.05"/>
  </joint>

  <link name="prlink4">
    <visual>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${boom_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="prj4" type="prismatic">
    <parent link="prlink4"/>
    <child link="prlink5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="10000" lower="0" upper="14" velocity="0.05"/>
  </joint>

  <link name="prlink5">
    <visual>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
      <mass value="${boom_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

<!-- start lidar-->

  <joint name="lidar_base_joint" type="continuous">
    <parent link="prlink5"/>
    <child link="lidar_base"/>
    <origin xyz="13.8 0.25 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.5" friction="0.0"/>
  </joint>

  <link name="lidar_base">
    <visual>
      <origin xyz="0 0 -0.125" rpy="0 0 0"/>
      <geometry>
        <box size="0.25 0.25 0.25"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="continuous">
    <parent link="lidar_base"/>
    <child link="lidar_mount"/>
    <origin xyz="0 0 -0.45" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="3.14"/>
  </joint>

  <link name="lidar_mount">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.1 0.4"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
  <VLP-16 parent="lidar_mount" name="velodyne" topic="velodyne_points" hz="10" samples="440">
    <origin xyz="0.02 0 -0.1" rpy="0 1.57 0" />
  </VLP-16>

<!--end lidar, start load-->

  <joint name="free_joint" type="continuous"> <!--free joint-->
    <parent link="prlink5"/>
    <child link="link4"/>
    <origin xyz="16.5 0 0" rpy="0 0 0"/> <!--originally 14.5-->
    <axis xyz="0 1 0"/>
    <dynamics damping="10.0" friction="0.5"/>
  </joint>

  <link name="link4"> <!--this is mini link-->
    <!-- <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual> -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="cable" type="prismatic">
    <parent link="link4"/>
    <child link="load"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000" lower="-60.0" upper="0.0" velocity="0.1"/>
    <dynamics damping="0.0" friction="2.0"/>
  </joint>

  <link name="load">
    <collision>
      <!-- <origin xyz="0 0 -1.5" rpy="0 0 0"/> -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!-- <box size="0.01 0.01 0.01"/> -->
        <box size="3.0 3.0 3.0"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="3.0 3.0 3.0"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="azimuth">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="elevation">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prj1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prj2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prj3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prj4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran7">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lidar_base_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor7">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran7">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lidar_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor7">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran8">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="free_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor8">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran9">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="cable">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor9">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
